"""
Critic Agent for AI Agent Benchmark system.

This agent is responsible for evaluating the **quality of review opinions**
generated by the Reviewer Agent.  Instead of critiquing code directly, it
acts as a meta-reviewer that:

- Assesses whether each reported review issue is a true positive or a false
  positive (误报).
- Identifies issues that were missed (漏报 / false negatives).
- Maintains a set of review standards (审查标准) to calibrate expectations.
- Provides actionable improvement suggestions for the review process.
- Generates structured evaluation reports.
"""

import asyncio
import re
from typing import Any, Dict, List, Optional, Tuple
import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

from .base_agent import BaseAgent, AgentMessage

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------ #
# Enums & data classes
# ------------------------------------------------------------------ #

class CriticismType(str, Enum):
    """Categories of evaluation feedback."""
    FALSE_POSITIVE = "false_positive"
    FALSE_NEGATIVE = "false_negative"
    SEVERITY_MISMATCH = "severity_mismatch"
    WRONG_CATEGORY = "wrong_category"
    MISSING_SUGGESTION = "missing_suggestion"
    DUPLICATE_ISSUE = "duplicate_issue"
    ACCURATE = "accurate"


class ReviewStandard(str, Enum):
    """Built-in review standards that the critic maintains."""
    NAMING_CONVENTION = "naming_convention"
    CODE_COMPLEXITY = "code_complexity"
    DOCUMENTATION = "documentation"
    SECURITY = "security"
    PERFORMANCE = "performance"
    BEST_PRACTICE = "best_practice"
    STYLE = "style"
    ERROR_HANDLING = "error_handling"
    DESIGN_PATTERN = "design_pattern"


@dataclass
class EvaluationItem:
    """Evaluation of a single review issue."""
    issue_id: str
    evaluation: CriticismType
    confidence: float  # 0.0 - 1.0
    reasoning: str
    suggested_severity: Optional[str] = None
    suggested_category: Optional[str] = None
    improvement_suggestion: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert evaluation item to dictionary."""
        result = {
            "issue_id": self.issue_id,
            "evaluation": self.evaluation.value,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
        }
        if self.suggested_severity is not None:
            result["suggested_severity"] = self.suggested_severity
        if self.suggested_category is not None:
            result["suggested_category"] = self.suggested_category
        if self.improvement_suggestion is not None:
            result["improvement_suggestion"] = self.improvement_suggestion
        return result


@dataclass
class MissedIssue:
    """An issue that was missed by the original review."""
    id: str
    standard: ReviewStandard
    expected_category: str
    description: str
    severity: str
    example: Optional[str] = None
    line_hint: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert missed issue to dictionary."""
        return {
            "id": self.id,
            "standard": self.standard.value,
            "expected_category": self.expected_category,
            "description": self.description,
            "severity": self.severity,
            "example": self.example,
            "line_hint": self.line_hint,
        }


@dataclass
class CriticismResult:
    """Complete evaluation result for a review."""
    overall_assessment: str
    score: float  # 0-100, higher = review quality is better
    evaluations: List[EvaluationItem]
    missed_issues: List[MissedIssue]
    strengths: List[str]
    weaknesses: List[str]
    recommendations: List[str]
    metrics: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        """Convert result to dictionary."""
        return {
            "overall_assessment": self.overall_assessment,
            "score": self.score,
            "evaluations": [e.to_dict() for e in self.evaluations],
            "missed_issues": [m.to_dict() for m in self.missed_issues],
            "strengths": self.strengths,
            "weaknesses": self.weaknesses,
            "recommendations": self.recommendations,
            "metrics": self.metrics,
        }


# ------------------------------------------------------------------ #
# Critic Agent
# ------------------------------------------------------------------ #

class CriticAgent(BaseAgent):
    """Agent responsible for evaluating the quality of review opinions.

    Core capabilities:
    - Evaluate whether each review issue is accurate, a false positive,
      or a false negative.
    - Identify missed issues by scanning the source code against review
      standards.
    - Provide improvement suggestions for the review process.
    - Maintain and evolve review standards.
    - Generate structured evaluation reports.

    Usage::

        critic = CriticAgent(name="critic_v2")
        await critic.initialize()

        result = await critic.run_task({
            "code": "...",
            "language": "python",
            "review_result": { ... },   # output from ReviewerAgent
        })
    """

    def __init__(
        self,
        name: str = "critic",
        message_queue=None,
        config: Optional[Dict[str, Any]] = None,
    ):
        """Initialize critic agent.

        Args:
            name: Agent name identifier.
            message_queue: Shared message queue for inter-agent communication.
            config: Optional configuration overrides.
        """
        super().__init__(name=name, agent_type="critic", message_queue=message_queue, config=config)

        # Review standards and thresholds
        self.review_standards = self._load_review_standards()

        # Statistics
        self.evaluations_completed = 0
        self.false_positives_detected = 0
        self.false_negatives_detected = 0

    # ------------------------------------------------------------------ #
    # Standards loading
    # ------------------------------------------------------------------ #

    def _load_review_standards(self) -> Dict[str, Any]:
        """Load review standards that define what a correct review should cover.

        Returns:
            Dictionary of review standards grouped by category.
        """
        return {
            ReviewStandard.NAMING_CONVENTION.value: {
                "description": "命名规范检查",
                "language_patterns": {
                    "python": {
                        "function": r"^[a-z_][a-z0-9_]*$",
                        "class": r"^[A-Z][a-zA-Z0-9]*$",
                        "variable": r"^[a-z_][a-z0-9_]*$",
                        "constant": r"^[A-Z_][A-Z0-9_]*$",
                    },
                    "java": {
                        "method": r"^[a-z][a-zA-Z0-9]*$",
                        "class": r"^[A-Z][a-zA-Z0-9]*$",
                        "variable": r"^[a-z][a-zA-Z0-9]*$",
                        "constant": r"^[A-Z_][A-Z0-9_]*$",
                    },
                },
            },
            ReviewStandard.CODE_COMPLEXITY.value: {
                "description": "代码复杂度检查",
                "thresholds": {
                    "max_function_length": 50,
                    "max_nesting_depth": 4,
                    "max_parameters": 5,
                },
            },
            ReviewStandard.DOCUMENTATION.value: {
                "description": "文档完整性检查",
                "rules": {
                    "python": ["public_function_docstring", "class_docstring"],
                    "java": ["public_method_javadoc", "class_javadoc"],
                },
            },
            ReviewStandard.SECURITY.value: {
                "description": "安全漏洞检查",
                "forbidden_patterns": {
                    "python": [
                        (r"eval\s*\(", "critical", "eval() 函数存在代码注入风险"),
                        (r"exec\s*\(", "critical", "exec() 函数存在代码注入风险"),
                        (r"pickle\.loads?\s*\(", "high", "pickle 反序列化不安全"),
                        (r"subprocess\.\w+\(.*shell\s*=\s*True", "high", "shell=True 存在命令注入风险"),
                    ],
                    "java": [
                        (r"Runtime\.getRuntime\(\)\.exec\(", "high", "直接调用系统命令存在安全风险"),
                        (r"ObjectInputStream", "high", "Java 反序列化可能存在漏洞"),
                    ],
                },
            },
            ReviewStandard.PERFORMANCE.value: {
                "description": "性能问题检查",
                "patterns": {
                    "python": [
                        (r"for\s+.*\s+in\s+range\(len\(", "warning", "使用 enumerate() 替代 range(len())"),
                        (r"\+\s*=\s*['\"]", "warning", "循环中字符串拼接效率低"),
                    ],
                },
            },
            ReviewStandard.BEST_PRACTICE.value: {
                "description": "最佳实践检查",
                "forbidden_patterns": {
                    "python": [
                        (r"except\s*:", "warning", "避免使用裸 except 子句"),
                        (r"from\s+\w+\s+import\s+\*", "warning", "避免通配符导入"),
                        (r"print\s*\(", "info", "生产代码应使用 logging"),
                    ],
                    "java": [
                        (r"System\.out\.print", "warning", "生产代码应使用日志框架"),
                        (r"catch\s*\(\s*Exception\s+", "warning", "避免捕获通用 Exception"),
                    ],
                },
            },
            ReviewStandard.STYLE.value: {
                "description": "代码风格检查",
                "thresholds": {
                    "python": {"max_line_length": 88},
                    "java": {"max_line_length": 120},
                },
            },
            ReviewStandard.ERROR_HANDLING.value: {
                "description": "错误处理检查",
                "patterns": {
                    "python": [
                        (r"except\s+\w+.*pass\s*$", "warning", "空的 except 块会吞没异常"),
                        (r"except\s*:", "error", "裸 except 子句会捕获所有异常"),
                    ],
                },
            },
            ReviewStandard.DESIGN_PATTERN.value: {
                "description": "设计模式检查",
                "patterns": {
                    "python": [
                        (r"def\s+\w+\s*\(.*=\s*(\[\]|\{\})\s*\)", "warning", "可变默认参数"),
                        (r"if\s+.*==\s*None", "info", "使用 is None 替代 == None"),
                        (r"if\s+.*!=\s*None", "info", "使用 is not None 替代 != None"),
                    ],
                },
            },
        }

    # ------------------------------------------------------------------ #
    # Process entry point
    # ------------------------------------------------------------------ #

    async def process(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Process a review evaluation task.

        The ``task`` dictionary should contain:

        - ``code`` (str): The source code that was reviewed.
        - ``language`` (str, optional): Programming language, defaults to ``"python"``.
        - ``review_result`` (dict): The review result from ReviewerAgent
          (output of ``ReviewerAgent.run_task()``).
        - ``file_path`` (str, optional): File path for context.
        - ``reviewer_agent_id`` (str, optional): ID of the reviewer being evaluated.

        Args:
            task: Task data dictionary.

        Returns:
            Dictionary containing the evaluation result.
        """
        code = task.get("code", "")
        language = task.get("language", "python")
        review_result = task.get("review_result", {})
        file_path = task.get("file_path")
        reviewer_agent_id = task.get("reviewer_agent_id", "unknown")

        logger.info(
            "Evaluating review quality for %s code (%d chars) from reviewer %s",
            language, len(code), reviewer_agent_id,
        )

        # Perform evaluation
        evaluation_result = await self._evaluate_review(
            code, language, review_result, file_path, reviewer_agent_id
        )

        # Update statistics
        self.evaluations_completed += 1
        for eval_item in evaluation_result.evaluations:
            if eval_item.evaluation == CriticismType.FALSE_POSITIVE:
                self.false_positives_detected += 1
            elif eval_item.evaluation == CriticismType.FALSE_NEGATIVE:
                self.false_negatives_detected += 1

        return evaluation_result.to_dict()

    # ------------------------------------------------------------------ #
    # Core evaluation pipeline
    # ------------------------------------------------------------------ #

    async def _evaluate_review(
        self,
        code: str,
        language: str,
        review_result: Dict[str, Any],
        file_path: Optional[str],
        reviewer_agent_id: str,
    ) -> CriticismResult:
        """Evaluate the quality of a review result.

        Args:
            code: The original source code that was reviewed.
            language: Programming language identifier.
            review_result: The structured review result from the Reviewer Agent.
            file_path: Optional file path.
            reviewer_agent_id: Identifier of the reviewer being evaluated.

        Returns:
            A ``CriticismResult`` with detailed evaluation.
        """
        evaluations: List[EvaluationItem] = []
        missed_issues: List[MissedIssue] = []

        # 1. Evaluate each reported issue
        reported_issues = review_result.get("issues", [])
        for issue in reported_issues:
            eval_item = await self._evaluate_issue(code, language, issue)
            evaluations.append(eval_item)

        # 2. Detect missed issues (false negatives)
        missed = await self._detect_missed_issues(code, language, reported_issues)
        missed_issues.extend(missed)

        # 3. Check for duplicates
        duplicate_evals = self._check_duplicates(reported_issues)
        evaluations.extend(duplicate_evals)

        # 4. Calculate score
        score = self._calculate_score(evaluations, missed_issues, len(reported_issues))

        # 5. Generate overall assessment
        overall_assessment = self._generate_overall_assessment(evaluations, missed_issues, score)

        # 6. Identify strengths and weaknesses
        strengths = self._identify_strengths(evaluations, missed_issues)
        weaknesses = self._identify_weaknesses(evaluations, missed_issues)

        # 7. Generate recommendations
        recommendations = self._generate_recommendations(evaluations, missed_issues, language)

        # 8. Calculate metrics
        metrics = self._calculate_metrics(evaluations, missed_issues, review_result)

        return CriticismResult(
            overall_assessment=overall_assessment,
            score=score,
            evaluations=evaluations,
            missed_issues=missed_issues,
            strengths=strengths,
            weaknesses=weaknesses,
            recommendations=recommendations,
            metrics=metrics,
        )

    # ------------------------------------------------------------------ #
    # Issue evaluation
    # ------------------------------------------------------------------ #

    async def _evaluate_issue(
        self,
        code: str,
        language: str,
        issue: Dict[str, Any],
    ) -> EvaluationItem:
        """Evaluate a single review issue for accuracy.

        Checks the issue against source code to determine whether it is a
        true positive, false positive, severity mismatch, etc.

        Args:
            code: The original source code.
            language: Programming language identifier.
            issue: A review issue dict from the Reviewer Agent.

        Returns:
            An ``EvaluationItem`` with the evaluation verdict.
        """
        issue_id = issue.get("id", "unknown")
        issue_message = issue.get("message", "")
        issue_category = issue.get("category", "")
        issue_severity = issue.get("severity", "info")
        code_snippet = issue.get("code_snippet")
        line_number = issue.get("line_number")

        # Verify the issue against the source code
        is_accurate = await self._verify_issue_accuracy(
            code, language, issue_category, issue_message, code_snippet, line_number
        )

        if is_accurate:
            # Check severity appropriateness
            severity_appropriate = self._check_severity_appropriateness(
                issue_category, issue_message, issue_severity
            )
            if severity_appropriate:
                return EvaluationItem(
                    issue_id=issue_id,
                    evaluation=CriticismType.ACCURATE,
                    confidence=0.9,
                    reasoning=f"审查意见 '{issue_message}' 准确，严重程度 '{issue_severity}' 合理",
                )
            else:
                return EvaluationItem(
                    issue_id=issue_id,
                    evaluation=CriticismType.SEVERITY_MISMATCH,
                    confidence=0.7,
                    reasoning=f"审查意见 '{issue_message}' 有效，但严重程度 '{issue_severity}' 不当",
                    suggested_severity=self._suggest_better_severity(issue_category, issue_message),
                )
        else:
            return EvaluationItem(
                issue_id=issue_id,
                evaluation=CriticismType.FALSE_POSITIVE,
                confidence=0.8,
                reasoning=f"审查意见 '{issue_message}' 在代码中未找到对应问题，可能是误报",
                improvement_suggestion="建议增强代码匹配逻辑的精确度",
            )

    async def _verify_issue_accuracy(
        self,
        code: str,
        language: str,
        category: str,
        message: str,
        code_snippet: Optional[str],
        line_number: Optional[int],
    ) -> bool:
        """Verify whether a review issue is actually present in the code.

        Args:
            code: Source code to check against.
            language: Programming language.
            category: Issue category (style, naming, complexity, etc.).
            message: Human-readable issue message.
            code_snippet: The code snippet mentioned in the issue.
            line_number: Line number referenced in the issue.

        Returns:
            ``True`` if the issue appears to be valid.
        """
        lines = code.split("\n")

        # If a specific line was referenced, verify it exists and matches
        if line_number is not None and 1 <= line_number <= len(lines):
            referenced_line = lines[line_number - 1]

            # For naming issues, verify the identifier exists
            if category == "naming":
                # Extract the identifier name from the message
                name_match = re.search(r"['\"](\w+)['\"]", message)
                if name_match:
                    identifier = name_match.group(1)
                    if identifier not in referenced_line and identifier not in code:
                        return False

            # For style issues with code snippet, verify presence
            if code_snippet and code_snippet.strip() not in referenced_line:
                # Allow some flexibility - the snippet might have been truncated
                if len(code_snippet.strip()) > 10:
                    return False

        # For pattern-based issues, verify the pattern exists in code
        if category == "best_practice":
            # Common patterns to verify
            if "eval()" in message and "eval(" not in code:
                return False
            if "except" in message and "except" not in code:
                return False
            if "通配符导入" in message and "import *" not in code:
                return False

        if category == "complexity":
            # For function length issues, try to verify
            if "过长" in message and line_number:
                # Check if there's actually a function around that line
                if line_number <= len(lines):
                    # Look backward for a def/function declaration
                    func_found = False
                    for i in range(max(0, line_number - 2), -1, -1):
                        if re.match(r"\s*(def|function|public|private)\s+", lines[i]):
                            func_found = True
                            break
                    if not func_found:
                        return False

        # Default: if we can't verify specifically, assume accurate
        return True

    def _check_severity_appropriateness(
        self,
        category: str,
        message: str,
        severity: str,
    ) -> bool:
        """Check whether the reported severity is appropriate for the category.

        Args:
            category: Issue category.
            message: Issue message for context.
            severity: Reported severity level.

        Returns:
            ``True`` if the severity seems appropriate.
        """
        # Define expected severity ranges for categories
        severity_ranges = {
            "style": {"min": "info", "max": "warning"},
            "naming": {"min": "info", "max": "info"},
            "documentation": {"min": "info", "max": "info"},
            "complexity": {"min": "warning", "max": "error"},
            "best_practice": {"min": "warning", "max": "error"},
        }

        severity_order = {"info": 0, "warning": 1, "error": 2, "critical": 3}

        expected = severity_ranges.get(category)
        if expected is None:
            return True  # No expectation for this category

        actual = severity_order.get(severity, 0)
        min_sev = severity_order.get(expected["min"], 0)
        max_sev = severity_order.get(expected["max"], 2)

        return min_sev <= actual <= max_sev

    def _suggest_better_severity(self, category: str, message: str) -> str:
        """Suggest a more appropriate severity level.

        Args:
            category: Issue category.
            message: Issue message for context.

        Returns:
            Suggested severity string.
        """
        if category in ("style", "naming", "documentation"):
            return "info"
        if category == "complexity":
            return "warning"
        if category == "best_practice":
            if "eval" in message.lower() or "exec" in message.lower():
                return "critical"
            return "warning"
        return "info"

    # ------------------------------------------------------------------ #
    # Missed issue detection (false negatives)
    # ------------------------------------------------------------------ #

    async def _detect_missed_issues(
        self,
        code: str,
        language: str,
        reported_issues: List[Dict[str, Any]],
    ) -> List[MissedIssue]:
        """Detect issues that should have been reported but were not.

        Scans the source code against all review standards and compares
        against what was actually reported.

        Args:
            code: Source code to scan.
            language: Programming language identifier.
            reported_issues: List of issues already reported by the Reviewer.

        Returns:
            List of ``MissedIssue`` objects representing missed findings.
        """
        missed: List[MissedIssue] = []

        # Build a set of reported issue messages for quick lookup
        reported_messages = {issue.get("message", "").lower() for issue in reported_issues}

        # Scan each standard for potential missed issues
        for standard_name, standard_config in self.review_standards.items():
            standard_missed = await self._scan_for_standard(
                code, language, standard_name, standard_config, reported_messages
            )
            missed.extend(standard_missed)

        return missed

    async def _scan_for_standard(
        self,
        code: str,
        language: str,
        standard_name: str,
        standard_config: Dict[str, Any],
        reported_messages: set,
    ) -> List[MissedIssue]:
        """Scan code against a specific review standard.

        Args:
            code: Source code to scan.
            language: Programming language identifier.
            standard_name: Name of the standard to check.
            standard_config: Configuration for this standard.
            reported_messages: Set of already-reported issue messages (lowered).

        Returns:
            List of missed issues for this standard.
        """
        missed: List[MissedIssue] = []
        lines = code.split("\n")

        # Check forbidden patterns
        forbidden = standard_config.get("forbidden_patterns", {}).get(language, [])
        for pattern, severity, description in forbidden:
            for i, line in enumerate(lines, 1):
                if re.search(pattern, line):
                    # Check if this was already reported
                    if not any(description.lower() in msg for msg in reported_messages):
                        missed.append(MissedIssue(
                            id=f"missed_{standard_name}_{i}",
                            standard=ReviewStandard(standard_name) if standard_name in [s.value for s in ReviewStandard] else ReviewStandard.BEST_PRACTICE,
                            expected_category=standard_name,
                            description=description,
                            severity=severity,
                            example=line.strip(),
                            line_hint=i,
                        ))

        # Check naming conventions
        if standard_name == ReviewStandard.NAMING_CONVENTION.value:
            patterns = standard_config.get("language_patterns", {}).get(language, {})
            if language == "python":
                for match in re.finditer(r"def\s+(\w+)\s*\(", code):
                    func_name = match.group(1)
                    expected = patterns.get("function", r"^[a-z_][a-z0-9_]*$")
                    if not re.match(expected, func_name):
                        if not any(func_name.lower() in msg for msg in reported_messages):
                            missed.append(MissedIssue(
                                id=f"missed_naming_func_{func_name}",
                                standard=ReviewStandard.NAMING_CONVENTION,
                                expected_category="naming",
                                description=f"函数名 '{func_name}' 不符合命名规范",
                                severity="info",
                                line_hint=code[:match.start()].count("\n") + 1,
                            ))

        # Check complexity thresholds
        if standard_name == ReviewStandard.CODE_COMPLEXITY.value:
            thresholds = standard_config.get("thresholds", {})
            max_func_len = thresholds.get("max_function_length", 50)

            if language == "python":
                func_start = None
                func_name = None
                for i, line in enumerate(lines):
                    match = re.match(r"^\s*def\s+(\w+)", line)
                    if match:
                        if func_name and func_start is not None:
                            func_len = i - func_start
                            if func_len > max_func_len:
                                if not any(f"过长" in msg and func_name in msg for msg in reported_messages):
                                    missed.append(MissedIssue(
                                        id=f"missed_complexity_{func_name}",
                                        standard=ReviewStandard.CODE_COMPLEXITY,
                                        expected_category="complexity",
                                        description=f"函数 '{func_name}' 过长 ({func_len} 行)",
                                        severity="warning",
                                        line_hint=func_start + 1,
                                    ))
                        func_name = match.group(1)
                        func_start = i

        return missed

    # ------------------------------------------------------------------ #
    # Duplicate detection
    # ------------------------------------------------------------------ #

    def _check_duplicates(self, reported_issues: List[Dict[str, Any]]) -> List[EvaluationItem]:
        """Check for duplicate review issues.

        Args:
            reported_issues: List of issues reported by the Reviewer.

        Returns:
            List of evaluation items marking duplicates.
        """
        evaluations: List[EvaluationItem] = []
        seen: Dict[str, List[str]] = {}

        for issue in reported_issues:
            key = f"{issue.get('category', '')}_{issue.get('message', '')}_{issue.get('line_number', '')}"
            issue_id = issue.get("id", "unknown")
            if key in seen:
                evaluations.append(EvaluationItem(
                    issue_id=issue_id,
                    evaluation=CriticismType.DUPLICATE_ISSUE,
                    confidence=0.95,
                    reasoning=f"与 {seen[key][0]} 重复",
                    improvement_suggestion="合并重复的审查意见",
                ))
            else:
                seen[key] = [issue_id]

        return evaluations

    # ------------------------------------------------------------------ #
    # Score calculation
    # ------------------------------------------------------------------ #

    def _calculate_score(
        self,
        evaluations: List[EvaluationItem],
        missed_issues: List[MissedIssue],
        total_reported: int,
    ) -> float:
        """Calculate review quality score (0-100).

        Scoring formula:
        - Start at 100
        - Deduct for false positives (-5 per issue)
        - Deduct for severity mismatches (-2 per issue)
        - Deduct for duplicates (-3 per issue)
        - Deduct for missed issues (-3 per missed issue)
        - Bonus for high accuracy ratio

        Args:
            evaluations: List of evaluation items.
            missed_issues: List of missed issues.
            total_reported: Total number of issues reported.

        Returns:
            Quality score between 0 and 100.
        """
        score = 100.0

        # Penalties for evaluation results
        penalties = {
            CriticismType.FALSE_POSITIVE: 5.0,
            CriticismType.SEVERITY_MISMATCH: 2.0,
            CriticismType.WRONG_CATEGORY: 3.0,
            CriticismType.MISSING_SUGGESTION: 1.0,
            CriticismType.DUPLICATE_ISSUE: 3.0,
            CriticismType.FALSE_NEGATIVE: 4.0,
        }

        for eval_item in evaluations:
            score -= penalties.get(eval_item.evaluation, 0.0)

        # Penalty for missed issues
        score -= len(missed_issues) * 3.0

        # Bonus for accuracy if there are evaluations
        accurate_count = sum(1 for e in evaluations if e.evaluation == CriticismType.ACCURATE)
        if evaluations:
            accuracy_ratio = accurate_count / len(evaluations)
            if accuracy_ratio > 0.9:
                score += 5.0  # Bonus for high accuracy
            elif accuracy_ratio < 0.5:
                score -= 10.0  # Penalty for low accuracy

        return max(0.0, min(100.0, score))

    # ------------------------------------------------------------------ #
    # Assessment generation
    # ------------------------------------------------------------------ #

    def _generate_overall_assessment(
        self,
        evaluations: List[EvaluationItem],
        missed_issues: List[MissedIssue],
        score: float,
    ) -> str:
        """Generate a human-readable overall assessment.

        Args:
            evaluations: List of evaluation items.
            missed_issues: List of missed issues.
            score: Calculated quality score.

        Returns:
            Overall assessment string.
        """
        false_positives = sum(1 for e in evaluations if e.evaluation == CriticismType.FALSE_POSITIVE)
        accurate = sum(1 for e in evaluations if e.evaluation == CriticismType.ACCURATE)

        parts = []
        parts.append(f"审查质量评分: {score:.1f}/100")
        parts.append(f"已评估 {len(evaluations)} 条审查意见 (其中 {accurate} 条准确)")
        parts.append(f"发现 {false_positives} 条误报")
        parts.append(f"发现 {len(missed_issues)} 条漏报")

        if score >= 85:
            parts.append("总体评价: 审查质量优秀")
        elif score >= 70:
            parts.append("总体评价: 审查质量良好，有少量改进空间")
        elif score >= 50:
            parts.append("总体评价: 审查质量一般，需要改进")
        else:
            parts.append("总体评价: 审查质量较差，需要大幅改进")

        return "。".join(parts) + "。"

    def _identify_strengths(
        self,
        evaluations: List[EvaluationItem],
        missed_issues: List[MissedIssue],
    ) -> List[str]:
        """Identify strengths in the review process.

        Args:
            evaluations: List of evaluation items.
            missed_issues: List of missed issues.

        Returns:
            List of strength descriptions.
        """
        strengths: List[str] = []

        accurate_count = sum(1 for e in evaluations if e.evaluation == CriticismType.ACCURATE)
        total = len(evaluations)

        if total > 0 and accurate_count / total > 0.8:
            strengths.append("审查意见准确率高 (>80%)")

        if not missed_issues:
            strengths.append("未遗漏重要的代码问题")

        if not any(e.evaluation == CriticismType.DUPLICATE_ISSUE for e in evaluations):
            strengths.append("审查意见无重复")

        severity_matches = sum(1 for e in evaluations if e.evaluation == CriticismType.ACCURATE)
        if total > 0 and severity_matches / total > 0.7:
            strengths.append("严重程度评估总体合理")

        if not strengths:
            strengths.append("审查覆盖了基本的代码规范检查")

        return strengths

    def _identify_weaknesses(
        self,
        evaluations: List[EvaluationItem],
        missed_issues: List[MissedIssue],
    ) -> List[str]:
        """Identify weaknesses in the review process.

        Args:
            evaluations: List of evaluation items.
            missed_issues: List of missed issues.

        Returns:
            List of weakness descriptions.
        """
        weaknesses: List[str] = []

        false_positives = sum(1 for e in evaluations if e.evaluation == CriticismType.FALSE_POSITIVE)
        if false_positives > 0:
            weaknesses.append(f"存在 {false_positives} 条误报，降低了审查可信度")

        severity_mismatches = sum(1 for e in evaluations if e.evaluation == CriticismType.SEVERITY_MISMATCH)
        if severity_mismatches > 0:
            weaknesses.append(f"存在 {severity_mismatches} 条严重程度不匹配的审查意见")

        duplicates = sum(1 for e in evaluations if e.evaluation == CriticismType.DUPLICATE_ISSUE)
        if duplicates > 0:
            weaknesses.append(f"存在 {duplicates} 条重复的审查意见")

        if missed_issues:
            weaknesses.append(f"遗漏了 {len(missed_issues)} 个代码问题")

        # Check missed issue categories
        missed_categories = set(m.standard.value for m in missed_issues)
        if missed_categories:
            weaknesses.append(f"漏报涉及的领域: {', '.join(missed_categories)}")

        if not weaknesses:
            weaknesses.append("暂未发现明显不足")

        return weaknesses

    def _generate_recommendations(
        self,
        evaluations: List[EvaluationItem],
        missed_issues: List[MissedIssue],
        language: str,
    ) -> List[str]:
        """Generate recommendations for improving the review process.

        Args:
            evaluations: List of evaluation items.
            missed_issues: List of missed issues.
            language: Programming language identifier.

        Returns:
            List of recommendation strings.
        """
        recommendations: List[str] = []

        false_positives = sum(1 for e in evaluations if e.evaluation == CriticismType.FALSE_POSITIVE)
        if false_positives > 0:
            recommendations.append(
                "减少误报: 增强代码匹配逻辑的精确度，在报告问题前验证代码片段确实存在"
            )

        severity_mismatches = sum(1 for e in evaluations if e.evaluation == CriticismType.SEVERITY_MISMATCH)
        if severity_mismatches > 0:
            recommendations.append(
                "校准严重程度: 根据问题类别调整严重程度评估，"
                "命名和风格问题通常为 info，复杂度和最佳实践问题通常为 warning"
            )

        # Recommendations based on missed issue categories
        missed_standards = set(m.standard.value for m in missed_issues)
        if ReviewStandard.SECURITY.value in missed_standards:
            recommendations.append("加强安全检查: 增加安全相关模式的检测覆盖")

        if ReviewStandard.DOCUMENTATION.value in missed_standards:
            recommendations.append("完善文档检查: 增加文档完整性的验证规则")

        if ReviewStandard.PERFORMANCE.value in missed_standards:
            recommendations.append("增强性能分析: 添加更多性能反模式的检测")

        if ReviewStandard.CODE_COMPLEXITY.value in missed_standards:
            recommendations.append("改进复杂度分析: 深化函数长度和嵌套深度的检查")

        # General recommendations
        if not recommendations:
            recommendations.append("审查质量良好，可继续优化以进一步提升准确性")

        return recommendations

    # ------------------------------------------------------------------ #
    # Metrics
    # ------------------------------------------------------------------ #

    def _calculate_metrics(
        self,
        evaluations: List[EvaluationItem],
        missed_issues: List[MissedIssue],
        review_result: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Calculate detailed evaluation metrics.

        Args:
            evaluations: List of evaluation items.
            missed_issues: List of missed issues.
            review_result: Original review result from the Reviewer.

        Returns:
            Dictionary of evaluation metrics.
        """
        total_reported = len(review_result.get("issues", []))
        total_evaluated = len(evaluations)

        # Count by evaluation type
        type_counts: Dict[str, int] = {}
        for eval_item in evaluations:
            eval_type = eval_item.evaluation.value
            type_counts[eval_type] = type_counts.get(eval_type, 0) + 1

        accurate = type_counts.get("accurate", 0)
        false_positives = type_counts.get("false_positive", 0)
        severity_mismatches = type_counts.get("severity_mismatch", 0)
        duplicates = type_counts.get("duplicate_issue", 0)

        # Missed issue categories
        missed_categories: Dict[str, int] = {}
        for missed in missed_issues:
            cat = missed.expected_category
            missed_categories[cat] = missed_categories.get(cat, 0) + 1

        # Precision and recall estimates
        precision = accurate / max(1, total_reported) if total_reported > 0 else 1.0
        false_negative_count = len(missed_issues)
        recall = accurate / max(1, accurate + false_negative_count) if (accurate + false_negative_count) > 0 else 1.0

        return {
            "total_reported_issues": total_reported,
            "total_evaluated": total_evaluated,
            "accurate_count": accurate,
            "false_positive_count": false_positives,
            "severity_mismatch_count": severity_mismatches,
            "duplicate_count": duplicates,
            "missed_issue_count": len(missed_issues),
            "missed_issue_categories": missed_categories,
            "estimated_precision": round(precision, 3),
            "estimated_recall": round(recall, 3),
            "evaluations_by_type": type_counts,
        }
